name: Go CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22' # তোমার Go ভার্সন

      # 3. Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # 4. Run tests
      - name: Run tests
        run: go test ./...

      # 5. Build binary
      - name: Build
        run: go build -o my-go-app .

      # 6. Deploy (Example: SSH to server)
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "my-go-app"
          target: "/home/${{ secrets.SERVER_USER }}/my-go-app"
