name: Go CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      # 3. Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # 4. Run tests
      - name: Run tests
        run: go test ./...

      # 5. Build binary
      - name: Build
        run: go build -o my-go-app .

      # 6. Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-go-app-binary
          path: my-go-app
